apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yutaro-test

resources:
  - job.yml
#  - deployment.yml
  - svc.yml
  - ingress.yml
  - env.yml

configMapGenerator:
  - name: test-conf
    files:
      - test.conf
  - name: index-html
    files:
      - index.html
  - name: create-cert-sh
    files:
      - create-cert.sh
  - name: init-sh
    files:
      - init.sh
