info:
  - namespace: application-1
    secret_name: rhems-getssl-cert
    domains:
      - rhems-getssl.example.com
  - namespace: application-2
    secret_name: rhems-getssl-2-cert
    domains:
      - rhems-getssl-2.example.com
  - namespace: application-3
    secret_name: rhems-getssl-3-cert
    domains:
      - rhems-getssl-3.example.com
