apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhems-getssl-go
  labels:
    app: rhems-getssl-go
spec:
  selector:
    matchLabels:
      app: rhems-getssl-go
  template:
    metadata:
      labels:
        app: rhems-getssl-go
    spec:
      containers:
        - name: rhems-getssl-go
          image: rhems-getssl
          imagePullPolicy: IfNotPresent
          workingDir: /root
          command: ["/root/server"]
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
            requests:
              cpu: 10m
              memory: 10Mi
          env:
            - name: TZ
              value: Asia/Tokyo
          envFrom:
            - secretRef:
                name: env
            - configMapRef:
                name: file-name
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 3
            failureThreshold: 1
            successThreshold: 1
          volumeMounts:
            - name: acme-challenge
              mountPath: /root/acme-challenge
      volumes:
        - name: acme-challenge
          configMap:
            name: acme-challenge
            defaultMode: 0755
