apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhems-getssl

resources:
  - cronjob.yml
  - env.yml
  - go.yml
  - svc.yml
  - rbac.yml
  - acme-challenge.yml
  - file-name.yml

images:
  - name: rhems-getssl
    newName: rhemsjapan/rhems-getssl
    newTag: latest

configMapGenerator:
  - name: config
    files:
      - config.yml
