#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled

_TAG=$(echo $IMAGE_NAME | cut -d ':' -f 2)

echo "---- check env -----"
echo $DOCKERFILE_PATH
echo ${_TAG}

docker buildx create --use --driver docker-container
docker buildx build --platform linux/amd64,linux/arm64 -f ${DOCKERFILE_PATH} -t ${MUTLI_ARC_IMAGE_NAME} . --push

#docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
#
#if [ ${_TAG} == "main" ]
#then
#    MUTLI_ARC_IMAGE_NAME=$(echo $IMAGE_NAME | sed 's/:main/:latest/g')
#    docker buildx create --use --driver docker-container
#    docker buildx build --platform linux/amd64,linux/arm64 -f ${DOCKERFILE_PATH} -t ${MUTLI_ARC_IMAGE_NAME} . --push
#fi


# echo "----- add tag -----"
# docker tag ${PRE_IMAGE_NAME} ${IMAGE_NAME}

# echo "====== inspect ======"
# docker buildx imagetools inspect $IMAGE_NAME
# docker buildx create --use
# docker build build --platform linux/arm64 -f $DOCKERFILE_PATH -t $IMAGE_NAME .
