info:
  - wildcard_domain: "*.example.com"
    wildcard_sans:
      - "*.test.example.com"
      - "*.mail.example.com"
    check_domains:
      - "test-getssl.example.com"
    secrets:
      - namespace: application-1
        secret_name: application-cert-id
      - namespace: application-2
        secret_name: application-cert-id-2
      - namespace: application-3
        secret_name: application-cert-id-3
    clbs:
      - load_balancer_id: lb-12345678
        listener_ids:
          - "lbl-12345678"
        region: ap-tokyo
