info:
  - wildcard_domain: "*.example.com"
    wildcard_sans:
      - "*.dev.example.com"
      - "*.stg.example.com"
    check_domains:
      - "rhems-getssl.example.com"
      - "rhems-getssl.dev.example.com"
      - "rhems-getssl.stg.example.com"
    secrets:
      - namespace: application
        secret_name: application-cert
      - namespace: application-dev
        secret_name: application-2-cert
      - namespace: application-stg
        secret_name: application-3-cert
    clbs:
      - load_balancer_id: lb-12345678
        listener_ids:
          - "lbl-12345678"
        region: ap-tokyo
