apiVersion: v1
kind: ServiceAccount
metadata:
  name: getssl-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-role-binding-getssl-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - name: getssl-job
    kind: ServiceAccount
    namespace: rhems-getssl

